version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports: ["5678:5678"]
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=n8ncitel.d3.works
      - WEBHOOK_URL=https://n8ncitel.d3.works/
      - NODE_FUNCTION_ALLOW_EXTERNAL=nodemailer,openai,pg
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
